default:
  image: python:latest

stages:
  - build
  - upload
  - release
  - pages




variables:
  # Package version can only contain numbers (0-9), and dots (.).
  # Must be in the format of X.Y.Z, i.e. should match /\A\d+\.\d+\.\d+\z/ regular expresion.
  # See https://docs.gitlab.com/ee/user/packages/generic_packages/#publish-a-package-file
  PACKAGE_VERSION: "0.0.1"
  DARWIN_AMD64_BINARY: "NodeEditor.exe"
  # LINUX_AMD64_BINARY: "myawesomerelease-linux-amd64-${PACKAGE_VERSION}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${PACKAGE_VERSION}"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build:
  stage: build
  image: 
    name: cdrx/pyinstaller-windows:python3
    entrypoint: ['/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0']
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  # cache:
  #   paths:
  #     - .cache/pip
  #     - venv/
  before_script:
  #   # - ls
    - python --version  # For debugging
    - python -m pip install --upgrade pip wheel setuptools
    # - pip install virtualenv
    # - virtualenv venv
    # - source venv/bin/activate
    - apt-get update -y && apt-get install -y libgl1
    # # - add-apt-repository ppa:deadsnakes/ppa   
    # # - apt install python3.7    
    # - pip install -r requirements.txt
  #   # - pip install pyinstaller
  #   # - echo ${PACKAGE_REGISTRY_URL}
  script:
    # - mkdir bin
    # - cd ../..
    # - ls
    - sh entrypoint-windows.sh
    # - cdrx/pyinstaller-windows
    # - /entrypoint-windows.sh
    # - pyinstaller main_node_editor.py --name NodeEditor --paths=./ --add-data "Config/*.cfg;Config" --add-data "font/*.ttf;font"
    - cp -r dist/windows/* bin

  artifacts:
    paths:
      - bin/


upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    # - |
      # IFS=$' \t\r\n'
    # - |
      # curl --proxy-insecure --proxy-cacert --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${DARWIN_AMD64_BINARY} "${PACKAGE_REGISTRY_URL}/${DARWIN_AMD64_BINARY}"
    - |
      curl --insecure --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${DARWIN_AMD64_BINARY} "${PACKAGE_REGISTRY_URL}/${DARWIN_AMD64_BINARY}"

release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  variables:
    ADDITIONAL_CA_CERT_BUNDLE: |
      -----BEGIN CERTIFICATE-----
      MIIHATCCBemgAwIBAgIQCVHyfJysMySuLSmH8kZvPDANBgkqhkiG9w0BAQsFADBg
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      d3cuZGlnaWNlcnQuY29tMR8wHQYDVQQDExZHZW9UcnVzdCBUTFMgUlNBIENBIEcx
      MB4XDTIzMDUwNDAwMDAwMFoXDTI0MDYwMzIzNTk1OVowWjELMAkGA1UEBhMCQ04x
      ETAPBgNVBAgTCFNoYW5naGFpMRswGQYDVQQKExJWaXJ0dW9zIENoaW5hIEx0ZC4x
      GzAZBgNVBAMMEioudmlydHVvc2dhbWVzLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBALyCj6v6dHjfVDblo6laNCBTHmo8THjF2MYHEye0E2r+CEY4
      hKYemi70Y9nkXiyxa3H07byhE0DrhY+JIhy9jLE3VxvXj+5hmNqrk4rFZw1vv+zX
      2LIQwroSiLbfpJacxXm/9h2dYpMUHD2qTzCjeSTovVJV+2ooLrm+IgnR314UJY18
      8b1LtWPdFMQSwUh8DfJY49ceLV5lHKPTeiBSctI9YObu1yWdVZWLfk6MjwHETeiF
      qq8Yt+Y0hVFF62y3oJEGVlyyUi8s3Dqgtg23ZE7xDZk51bEvWEDA8Rrdnbt8fBz9
      Ui9HFwuzpk0t0z5UJBK7r6ZoTgjQsEr6Dc/uja0CAwEAAaOCA7swggO3MB8GA1Ud
      IwQYMBaAFJRP1F2L5KTipoD+/dj5AO+jvgJXMB0GA1UdDgQWBBSdgNIjci6ijcV4
      pcOtH/Zod3XaDTCBvAYDVR0RBIG0MIGxghIqLnZpcnR1b3NnYW1lcy5jb22CECou
      dmlydHVvcy5jb20uY26CEyoudmlydHVvcy1zcGFyeC5jb22CEHZpcnR1b3NnYW1l
      cy5jb22CFHd3dy52aXJ0dW9zZ2FtZXMuY29tgg52aXJ0dW9zLmNvbS5jboISd3d3
      LnZpcnR1b3MuY29tLmNughF2aXJ0dW9zLXNwYXJ4LmNvbYIVd3d3LnZpcnR1b3Mt
      c3BhcnguY29tMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
      KwYBBQUHAwIwPwYDVR0fBDgwNjA0oDKgMIYuaHR0cDovL2NkcC5nZW90cnVzdC5j
      b20vR2VvVHJ1c3RUTFNSU0FDQUcxLmNybDA+BgNVHSAENzA1MDMGBmeBDAECAjAp
      MCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwdgYIKwYB
      BQUHAQEEajBoMCYGCCsGAQUFBzABhhpodHRwOi8vc3RhdHVzLmdlb3RydXN0LmNv
      bTA+BggrBgEFBQcwAoYyaHR0cDovL2NhY2VydHMuZ2VvdHJ1c3QuY29tL0dlb1Ry
      dXN0VExTUlNBQ0FHMS5jcnQwCQYDVR0TBAIwADCCAYEGCisGAQQB1nkCBAIEggFx
      BIIBbQFrAHcAdv+IPwq2+5VRwmHM9Ye6NLSkzbsp3GhCCp/mZ0xaOnQAAAGH5N9Z
      XwAABAMASDBGAiEA2pZVRe9QhSNAeMW4OYDEMk57p2B24wGMoYzkp4OqDCUCIQCU
      igUo2GLIC6B0Wj006279oUAglSEe1aFgOUXXAh/6+gB3AHPZnokbTJZ4oCB9R53m
      ssYc0FFecRkqjGuAEHrBd3K1AAABh+TfWUkAAAQDAEgwRgIhAJaNPzZ5tb5LH+TD
      IwJFq2ut8n1KqZjnUd1tVpqamuiCAiEA798b/DfyX5zbV3pj5dR7NeWqh0vsWujs
      8S7AjK59O/UAdwBIsONr2qZHNA/lagL6nTDrHFIBy1bdLIHZu7+rOdiEcwAAAYfk
      31kuAAAEAwBIMEYCIQDXym0+zvdlK47Cnnd9Rdz4ym6oZ5GGrGnX/qlIVtiKjAIh
      AOozh/rhH5FhBsmRdEbVPDAyNKQvZqiYLU1fU6eedhikMA0GCSqGSIb3DQEBCwUA
      A4IBAQBx8XsLepj6EM0Jlk2JjclcS8WSwORW0GYY1ld1LJcbxcQxr1qIfrL0Ptqn
      EDEkHXobDjON9PLf3ziaSnkH6qnd01MkL41tQuuoeXi1oBekqOWv9SRGGfXzQQut
      E+ZePzucUQjxBTXYPuVj4VzOysd4ysnJBrxgltULRm2VyQDeeaFVwSnj+RVzTaLG
      HqlBEL7Fj8WB77RZPFDNqQ544ws1L+xVwQWIjP89uKPOJc0KhgdmAhmqX86PxG2d
      /bqVXyNrTGsjqOHGiRo3hSMe79RTaLSC706MEqcjLaoCXIznr9zC8/hw/f/RGCVh
      go1r8tIKYFpXvYNkEaKeWvyIw3As
      -----END CERTIFICATE-----
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${DARWIN_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${DARWIN_AMD64_BINARY}\"}"
        # --assets-link "{\"name\":\"${LINUX_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}\"}"

pages:
  stage: pages
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - apt-get update && apt-get install -y libgl1
    - pip install -r requirements.txt
    - pip install sphinx sphinx-book-theme sphinx-autodoc-typehints myst-nb sphinx-thebe
    - pip install pyinstaller

  script:
    - cd docs
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

